### ISSUE TITLE
Error to run

### ISSUE THREAD

**Issue by RafaelPlantard** [hurbes/swift-app-pipeline-action#9]
Log:
security: unable to open "/Users/runner/Library/MobileDevice/Provisioning Profiles/build_pp.mobileprovision" for reading: No such file or directory

```
name: Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: hurbes/swift-app-pipeline-action@v0.2.0
      with:
        project-name: 'ProjectName'
        scheme-name: 'SchemeName'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        create-release: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run-lint: 'true'
        comment-on-pr: 'true'
        pr-comment-template: 'New build {build-number} is ready!'

```
